# two nodes (one worker) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#networking:
#  disableDefaultCNI: true        # default CNI will not be installed
#  kubeProxyMode: "nftables"      # set to "none" to disable kube-proxy
#  podSubnet: "10.244.0.0/16"
#  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
